// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqeuagdreaawywxecgee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xZXVhZ2RyZWFhd3l3eGVjZ2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODA2MTQsImV4cCI6MjA1ODY1NjYxNH0.RpLam4uWCQfhIqDa4Yy2TUIMvBkdW7zv6GYAU4o4j_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);